/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BestSellingWidget: typeof import('./src/components/dashboard/BestSellingWidget.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb.vue')['default']
    Button: typeof import('primevue/button')['default']
    Dropdown: typeof import('primevue/dropdown')['default']
    FeaturesWidget: typeof import('./src/components/landing/FeaturesWidget.vue')['default']
    FloatingConfigurator: typeof import('./src/components/FloatingConfigurator.vue')['default']
    FooterWidget: typeof import('./src/components/landing/FooterWidget.vue')['default']
    HeroWidget: typeof import('./src/components/landing/HeroWidget.vue')['default']
    HighlightsWidget: typeof import('./src/components/landing/HighlightsWidget.vue')['default']
    Iqa_Checklist_Page: typeof import('./src/components/IQA_Checklist/Iqa_Checklist_Page.vue')['default']
    'Manage.Material_Page': typeof import('./src/components/Manage_Material/Manage.Material_Page.vue')['default']
    'Manual.Receive.List_Page': typeof import('./src/components/Receice_Manual/Manual.Receive.List_Page.vue')['default']
    'Materials.Split_Delail_Page': typeof import('./src/components/Split_Materials/Materials.Split_Delail_Page.vue')['default']
    'Materials.Split_Page': typeof import('./src/components/Split_Materials/Materials.Split_Page.vue')['default']
    Mc_Transaction: typeof import('./src/components/Transaction_Material/Mc_Transaction.vue')['default']
    Mc_view_Iqa: typeof import('./src/components/IQA_Checklist/Mc_view_Iqa.vue')['default']
    NotificationsWidget: typeof import('./src/components/dashboard/NotificationsWidget.vue')['default']
    PricingWidget: typeof import('./src/components/landing/PricingWidget.vue')['default']
    Prod_Transaction: typeof import('./src/components/Transaction_Material/Prod_Transaction.vue')['default']
    Receive_mat_Page: typeof import('./src/components/Receice/Receive_mat_Page.vue')['default']
    'Receive.Detail_Page': typeof import('./src/components/Receice/Receive.Detail_Page.vue')['default']
    'Receive.Manual_Page': typeof import('./src/components/Receice_Manual/Receive.Manual_Page.vue')['default']
    RecentSalesWidget: typeof import('./src/components/dashboard/RecentSalesWidget.vue')['default']
    Request_Material: typeof import('./src/components/Transaction_Material/Request_Material.vue')['default']
    RevenueStreamWidget: typeof import('./src/components/dashboard/RevenueStreamWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    StatsWidget: typeof import('./src/components/dashboard/StatsWidget.vue')['default']
    Testvue: typeof import('./src/components/IQA_Checklist/testvue.vue')['default']
    TopbarWidget: typeof import('./src/components/landing/TopbarWidget.vue')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
